#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDemoWithDBMLClass.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Collage Master")]
	public partial class Student_MasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudent_Master(Student_Master instance);
    partial void UpdateStudent_Master(Student_Master instance);
    partial void DeleteStudent_Master(Student_Master instance);
    #endregion
		
		public Student_MasterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Collage_MasterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Student_MasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Student_MasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Student_MasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Student_MasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Student_Master> Student_Masters
		{
			get
			{
				return this.GetTable<Student_Master>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllStudentMaster")]
		public ISingleResult<Student_Master> SelectAllStudentMaster(int stdid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Student_Master>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student_Master")]
	public partial class Student_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _StdID;
		
		private string _StdName;
		
		private System.Nullable<decimal> _StdContactNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStdIDChanging(decimal value);
    partial void OnStdIDChanged();
    partial void OnStdNameChanging(string value);
    partial void OnStdNameChanged();
    partial void OnStdContactNoChanging(System.Nullable<decimal> value);
    partial void OnStdContactNoChanged();
    #endregion
		
		public Student_Master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdID", AutoSync=AutoSync.OnInsert, DbType="Decimal(10,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal StdID
		{
			get
			{
				return this._StdID;
			}
			set
			{
				if ((this._StdID != value))
				{
					this.OnStdIDChanging(value);
					this.SendPropertyChanging();
					this._StdID = value;
					this.SendPropertyChanged("StdID");
					this.OnStdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdName", DbType="VarChar(50)")]
		public string StdName
		{
			get
			{
				return this._StdName;
			}
			set
			{
				if ((this._StdName != value))
				{
					this.OnStdNameChanging(value);
					this.SendPropertyChanging();
					this._StdName = value;
					this.SendPropertyChanged("StdName");
					this.OnStdNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdContactNo", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> StdContactNo
		{
			get
			{
				return this._StdContactNo;
			}
			set
			{
				if ((this._StdContactNo != value))
				{
					this.OnStdContactNoChanging(value);
					this.SendPropertyChanging();
					this._StdContactNo = value;
					this.SendPropertyChanged("StdContactNo");
					this.OnStdContactNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
