#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDemoWithDBMLClass.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tempdb")]
	public partial class StudentDetailsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOLLAGE_MASTER(COLLAGE_MASTER instance);
    partial void UpdateCOLLAGE_MASTER(COLLAGE_MASTER instance);
    partial void DeleteCOLLAGE_MASTER(COLLAGE_MASTER instance);
    #endregion
		
		public StudentDetailsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["tempdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDetailsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDetailsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDetailsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentDetailsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COLLAGE_MASTER> COLLAGE_MASTERs
		{
			get
			{
				return this.GetTable<COLLAGE_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COLLAGE_MASTER")]
	public partial class COLLAGE_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StdID;
		
		private string _StdName;
		
		private string _StdAddress;
		
		private System.Nullable<decimal> _StdContactNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStdIDChanging(int value);
    partial void OnStdIDChanged();
    partial void OnStdNameChanging(string value);
    partial void OnStdNameChanged();
    partial void OnStdAddressChanging(string value);
    partial void OnStdAddressChanged();
    partial void OnStdContactNoChanging(System.Nullable<decimal> value);
    partial void OnStdContactNoChanged();
    #endregion
		
		public COLLAGE_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StdID
		{
			get
			{
				return this._StdID;
			}
			set
			{
				if ((this._StdID != value))
				{
					this.OnStdIDChanging(value);
					this.SendPropertyChanging();
					this._StdID = value;
					this.SendPropertyChanged("StdID");
					this.OnStdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdName", DbType="VarChar(100)")]
		public string StdName
		{
			get
			{
				return this._StdName;
			}
			set
			{
				if ((this._StdName != value))
				{
					this.OnStdNameChanging(value);
					this.SendPropertyChanging();
					this._StdName = value;
					this.SendPropertyChanged("StdName");
					this.OnStdNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdAddress", DbType="VarChar(MAX)")]
		public string StdAddress
		{
			get
			{
				return this._StdAddress;
			}
			set
			{
				if ((this._StdAddress != value))
				{
					this.OnStdAddressChanging(value);
					this.SendPropertyChanging();
					this._StdAddress = value;
					this.SendPropertyChanged("StdAddress");
					this.OnStdAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StdContactNo", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> StdContactNo
		{
			get
			{
				return this._StdContactNo;
			}
			set
			{
				if ((this._StdContactNo != value))
				{
					this.OnStdContactNoChanging(value);
					this.SendPropertyChanging();
					this._StdContactNo = value;
					this.SendPropertyChanged("StdContactNo");
					this.OnStdContactNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
