//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class tempdbEntities3 : DbContext
    {
        public tempdbEntities3()
            : base("name=tempdbEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLLAGE_MASTER> COLLAGE_MASTER { get; set; }
    
        public virtual ObjectResult<SelectAllCOLLAGE_MASTER_Result> SelectAllCOLLAGE_MASTER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllCOLLAGE_MASTER_Result>("SelectAllCOLLAGE_MASTER");
        }
    }
}
