<?xml version="1.0" encoding="utf-8"?><Database Name="demo_product" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DIT-DESKTOP-SER;Initial Catalog=demo_product;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="demo_productConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Category_CategoryProductRelation" Member="CategoryProductRelations" ThisKey="CategoryId" OtherKey="Category1_ID" Type="CategoryProductRelation" />
      <Association Name="Category_CategoryProductRelation1" Member="CategoryProductRelations1" ThisKey="CategoryId" OtherKey="Category2_ID" Type="CategoryProductRelation" />
      <Association Name="Category_Product" Member="Products" ThisKey="CategoryId" OtherKey="CategoryId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryProductRelations" Member="CategoryProductRelations">
    <Type Name="CategoryProductRelation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category1_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category2_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_CategoryProductRelation" Member="Category" ThisKey="Category1_ID" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
      <Association Name="Category_CategoryProductRelation1" Member="Category1" ThisKey="Category2_ID" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_Category_DeleteByID" Method="SP_Category_DeleteByID">
    <Parameter Name="CatID1" Parameter="catID1" Type="System.Int32" DbType="Int" />
    <Parameter Name="Res" Parameter="res" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>